# Generated by Django 5.0.6 on 2024-09-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complete',
            options={'ordering': ('-complete_timestamp',), 'verbose_name': 'Complete', 'verbose_name_plural': 'Completes'},
        ),
    ]
