# Generated by Django 5.0.6 on 2024-09-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_alter_complete_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complete',
        ),
    ]
