POST http://127.0.0.1:8000/login 
Content-Type: application/json

{  "username": "chris1", "password": "TGoheen5", "email": "chris@example.com" }


###

POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "chris1", "password": "TGoheen5", "email": "chris@example.com" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json 
Authorization: Token a09e58f8a3ff6eb8a4b786c37b6161133bdccb7f